apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: document-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: agent-platform
  source:
    repoURL: https://github.com/trajeshbe/ai-adoption.git
    targetRevision: HEAD
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
