apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - otel-collector-config.yaml
  - grafana-datasources.yaml
  - grafana-dashboards-configmap.yaml
  - service-monitors.yaml
  - slo-rules.yaml
  - grafana-alerts.yaml

commonLabels:
  app.kubernetes.io/component: observability
