# =============================================================================
# GCP Simple Deployment -- Single Compute Engine VM
#
# Deploys the AI Agent Platform on a single VM using docker-compose.
# Suitable for demos, development, and small-team usage.
#
# Usage:
#   terraform init
#   terraform apply -var="project=my-gcp-project" \
#                   -var="repo_url=https://github.com/org/ai-adoption.git" \
#                   -var="ssh_user=deploy" \
#                   -var="ssh_public_key=$(cat ~/.ssh/id_ed25519.pub)"
# =============================================================================

terraform {
  required_version = ">= 1.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project
  region  = var.region
  zone    = var.zone
}

# ---------------------------------------------------------------------------
# Locals
# ---------------------------------------------------------------------------

locals {
  # Fall back to the public IP when no domain is provided
  site_domain = var.domain != "" ? var.domain : google_compute_address.ai_platform.address

  labels = {
    app        = "ai-agent-platform"
    managed-by = "terraform"
    env        = "simple"
  }
}

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------

resource "google_compute_address" "ai_platform" {
  name        = "ai-platform-ip"
  description = "Static external IP for the AI Agent Platform VM"
  region      = var.region
}

resource "google_compute_firewall" "ai_platform" {
  name        = "ai-platform-allow-web-ssh"
  network     = "default"
  description = "Allow HTTP, HTTPS, and SSH traffic to the AI Agent Platform VM"

  allow {
    protocol = "tcp"
    ports    = ["22", "80", "443"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["ai-platform"]
}

# ---------------------------------------------------------------------------
# Compute Engine Instance
# ---------------------------------------------------------------------------

resource "google_compute_instance" "ai_platform" {
  name         = "ai-agent-platform"
  machine_type = var.machine_type
  zone         = var.zone

  tags   = ["ai-platform"]
  labels = local.labels

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2404-lts-amd64"
      size  = var.disk_size
      type  = "pd-balanced"
    }
  }

  network_interface {
    network = "default"

    access_config {
      nat_ip = google_compute_address.ai_platform.address
    }
  }

  metadata = {
    ssh-keys = "${var.ssh_user}:${var.ssh_public_key}"
  }

  metadata_startup_script = <<-SCRIPT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/startup-script.log 2>&1

    echo "=== AI Agent Platform startup script ==="
    echo "Started at: $(date -u)"

    # -----------------------------------------------------------------------
    # 1. Install Docker
    # -----------------------------------------------------------------------
    if ! command -v docker &>/dev/null; then
      echo "Installing Docker..."
      apt-get update -y
      apt-get install -y ca-certificates curl gnupg lsb-release

      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg

      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list

      apt-get update -y
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

      systemctl enable docker
      systemctl start docker

      # Allow the SSH user to run docker without sudo
      usermod -aG docker "${var.ssh_user}" || true
    fi

    # -----------------------------------------------------------------------
    # 2. Clone the repository
    # -----------------------------------------------------------------------
    REPO_DIR="/home/${var.ssh_user}/kiaa/ai-adoption"

    if [ ! -d "$REPO_DIR" ]; then
      echo "Cloning repository..."
      apt-get install -y git
      git clone "${var.repo_url}" "$REPO_DIR"
    else
      echo "Repository already exists, pulling latest..."
      cd "$REPO_DIR" && git pull --ff-only || true
    fi

    cd "$REPO_DIR"

    # -----------------------------------------------------------------------
    # 3. Write .env file
    # -----------------------------------------------------------------------
    echo "Writing .env file..."
    cat > .env <<ENV
    # Generated by Terraform startup script -- $(date -u)
    SITE_DOMAIN=${local.site_domain}
    PUBLIC_IP=${google_compute_address.ai_platform.address}
    NEXT_PUBLIC_GRAPHQL_URL=http://${local.site_domain}:8050/graphql
    ENV

    # -----------------------------------------------------------------------
    # 4. Start the platform
    # -----------------------------------------------------------------------
    echo "Starting AI Agent Platform via docker compose..."
    docker compose \
      -f docker-compose.yml \
      -f docker-compose.cpu.yml \
      --profile web \
      up -d --build

    echo "=== Startup complete at: $(date -u) ==="
  SCRIPT

  # Allow stopping the instance for resize without destroying it
  allow_stopping_for_update = true

  lifecycle {
    ignore_changes = [
      # Don't re-run startup script on every apply after initial creation
      metadata_startup_script,
    ]
  }
}
